http:
  host: 'localhost'
  port: 3000
db:
  mongodb:
    uri: 'mongodb+srv://ichikyube:kucingkucing@cluster0.scvmkyg.mongodb.net/catlibs'
    host: localhost
    port: 27017
    database: catlibs
    username: ichikyube
    password: kucingkucing

mongoose:
  connectTimeout: 10000
  socketTimeout: 30000
  useNewUrlParser: true
  useUnifiedTopology: true

elasticsearch:
  node: 'http://localhost:9200'
  host: elasticsearch
  port: 9200

session:
  secret: 'keyboard cat'
  resave: false
  saveUninitialized: false
  store:
    collection: 'session'
  cookie:
    secure: false
    maxAge: 86400000 # 1 day in milliseconds
